name: Auto Assign Issue

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assign:
    if: |
      github.event.issue.pull_request == null &&
      startsWith(github.event.comment.body, '/assign')
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const username = context.payload.comment.user.login;

            // Get issue
            const { data: issue } =
              await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });

            // Check if user is already assigned
            const alreadyAssigned = issue.assignees.some(
              assignee => assignee.login === username
            );

            if (alreadyAssigned) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `⚠️ @${username}, you are already assigned to this issue.`
              });

              return;
            }

            // Only one assignee is allowed for every issue
            if (issue.assignees.length > 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `⚠️ This issue is already assigned to ${
                  issue.assignees
                    .map(a => '@' + a.login)
                    .join(', ')
                }.`
              });

              return;
            }

            // Assign user
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: [username]
            });

            const message =
              `🎉 Assigned to @${username}!

              Please follow the contribution workflow:

              1. 🍴 Fork the repository
              2. ⭐ Star the repository
              3. 🌿 Create a new branch (Optional)
              4. ✏️ Make your changes
              5. 💾 Commit your changes
              6. 🚀 Push your branch
              7. 🔄 Create a Pull Request

              Please link this issue in your Pull Request using:

              \`Closes #${issueNumber}\`

              Good luck and happy contributing! 🚀`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });
